-- Q1 - WHICH EMPLOYEE HAS SOLD THE MOST?
/*
IN GENERAL, STEPHENS JON TENDS TO CONTRIBUTE SIGNIFICANTLY MORE TO SALES COMPARED TO THE REST OF THE STAFF. NOTABLY, IN THE MONTH OF MAY, THE GAP IN HIS FAVOR IS GREATER COMPARED TO OTHER MONTHS.
*/

WITH P1 AS (
    SELECT 
        DATE_TRUNC('MONTH', P.PAYMENT_DATE) + INTERVAL '1 MONTH' - INTERVAL '1 SECOND' AS PAYMENT_DATE_EOM,
        P.STAFF_ID,
        P.AMOUNT
    FROM PAYMENT P
),
P2 AS (
    SELECT 
        PAYMENT_DATE_EOM,
        SUM(P1.AMOUNT) AS AMT_TOT_MONTH
    FROM P1
    GROUP BY PAYMENT_DATE_EOM
)
SELECT 
    P1.PAYMENT_DATE_EOM,
    CONCAT(S.LAST_NAME, ' ', S.FIRST_NAME) AS EMPLOYEE_NAME,
    SUM(AMOUNT) AS AMT_STAFF,
    MAX(P2.AMT_TOT_MONTH) AS AMT_TOT_MONTH,
    SUM(AMOUNT)::DECIMAL / MAX(P2.AMT_TOT_MONTH) AS PERC_PROFIT_PER_STAFF
FROM STAFF S
JOIN P1 ON S.STAFF_ID = P1.STAFF_ID 
JOIN P2 ON P1.PAYMENT_DATE_EOM = P2.PAYMENT_DATE_EOM
GROUP BY P1.PAYMENT_DATE_EOM, S.STAFF_ID, CONCAT(S.LAST_NAME, ' ', S.FIRST_NAME)
ORDER BY P1.PAYMENT_DATE_EOM, CONCAT(S.LAST_NAME, ' ', S.FIRST_NAME);

-- Q2 - IS IT POSSIBLE TO OPTIMIZE THE FILM INVENTORY?
/*
4.2% OF THE FILMS DO NOT HAVE EXCESS COPIES BUT HAVE NOT HAD ANY RENTALS AND ARE NOT IN THE INVENTORY. I SUGGEST UPDATING THE FILM LIST TO REMOVE THEM.

76.10% OF THE FILMS HAVE ONE MORE COPY THAN THE HISTORICAL MAXIMUM OF CONCURRENT RENTALS. THIS IS CONSIDERED THE STANDARD AND ENSURES AN ADDITIONAL COPY IN CASE OF UNUSUAL DEMAND.

THE REMAINING 19.70% OF THE FILMS HAVE 2 OR MORE COPIES IN EXCESS COMPARED TO THE HISTORICAL MAXIMUM OF CONCURRENT RENTALS. HERE, IT MIGHT BE POSSIBLE TO OPTIMIZE BY SELLING THE EXCESS COPIES, THUS REDUCING STORAGE COSTS OR POTENTIAL WASTE IN FUTURE PURCHASES OF UNNECESSARY COPIES.
*/

WITH 
-- RENTALS WITH FILM INFO
T0 AS (
    SELECT 
        R1.RENTAL_ID,
        R1.RENTAL_DATE,
        R1.RETURN_DATE,
        R1.INVENTORY_ID,
        I.FILM_ID
    FROM RENTAL R1
    JOIN INVENTORY I ON R1.INVENTORY_ID = I.INVENTORY_ID 
),
-- RENTALS WITH DATA ON PARALLEL RENTALS
T2 AS (
    SELECT 
        T0.RENTAL_ID,
        T0.FILM_ID,
        COUNT(DISTINCT T1.INVENTORY_ID) AS PARALLEL_RENTAL
    FROM T0
    LEFT JOIN T0 T1 ON T0.RENTAL_ID <> T1.RENTAL_ID
    AND T0.FILM_ID = T1.FILM_ID
    AND T1.RENTAL_DATE BETWEEN T0.RENTAL_DATE AND T0.RETURN_DATE
    GROUP BY T0.RENTAL_ID, T0.FILM_ID
    ORDER BY T0.RENTAL_ID
),
-- MAXIMUM PARALLEL RENTALS PER FILM
T3 AS (
    SELECT 
        FILM_ID,
        MAX(PARALLEL_RENTAL) AS MAX_PARALLEL_RENTAL
    FROM T2
    GROUP BY FILM_ID
),
-- COPIES IN STOCK PER FILM
T4 AS (
    SELECT 
        F.FILM_ID,
        COUNT(I.INVENTORY_ID) AS COPIES_IN_STOCK
    FROM FILM F
    LEFT JOIN INVENTORY I ON F.FILM_ID = I.FILM_ID
    GROUP BY F.FILM_ID
),
T5 AS (
    -- BASE DATA WITH METRICS OF INTEREST
    SELECT 
        T3.FILM_ID,
        T3.MAX_PARALLEL_RENTAL,
        T4.COPIES_IN_STOCK,
        T4.COPIES_IN_STOCK - T3.MAX_PARALLEL_RENTAL AS EXCESS_COPIES
    FROM T3
    LEFT JOIN T4 ON T3.FILM_ID = T4.FILM_ID
),
T6 AS (
    -- DETAIL PER FILM WITH COMPLETE METRICS
    SELECT 
        F.FILM_ID,
        F.TITLE,
        COALESCE(T5.MAX_PARALLEL_RENTAL, 0) AS MAX_PARALLEL_RENTAL,
        COALESCE(T5.COPIES_IN_STOCK, 0) AS COPIES_IN_STOCK,
        COALESCE(T5.EXCESS_COPIES, 0) AS EXCESS_COPIES
    FROM FILM F
    LEFT JOIN T5 ON F.FILM_ID = T5.FILM_ID
    ORDER BY COALESCE(T5.EXCESS_COPIES, 0) DESC
)
SELECT 
    EXCESS_COPIES,
    MAX((SELECT COUNT(*) FROM FILM)) AS TOTAL_FILMS,
    COUNT(*) AS FILM_COUNT_PER_CATEGORY,
    COUNT(*)::DECIMAL / MAX((SELECT COUNT(*) FROM FILM)) AS PERC_FILMS_PER_CATEGORY
FROM T6
GROUP BY EXCESS_COPIES;

-- Q3 - HOW IS THE DAILY PAYMENT TREND COMPARED TO THE PREVIOUS DAY DIVIDED BY MOVIE RATING?
/*
ANALYZING THE GRAPH, IT IS POSSIBLE TO NOTICE A VERY INCONSISTENT TREND. IT IS EVIDENT FROM THE GRAPH THAT WITHIN THE SAMPLE
THERE IS A POSSIBLE PATTERN CHARACTERIZED BY A SIGNIFICANT DROP IN SALES OF ABOUT 90% REGARDLESS OF THE MOVIE RATING, FOLLOWED BY
CONSIDERABLE SALES PEAKS REACHING INCREASES IN THE ORDER OF 700% COMPARED TO THE PREVIOUS DAY.
*/

WITH T0 AS (
    SELECT 
        DATE_TRUNC('DAY', P.PAYMENT_DATE) AS REF_DATE,
        F.RATING,
        P.AMOUNT
    FROM PAYMENT P
    JOIN RENTAL R ON P.RENTAL_ID = R.RENTAL_ID
    JOIN INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
    JOIN FILM F ON I.FILM_ID = F.FILM_ID
),
T1 AS (
    SELECT 
        REF_DATE,
        RATING,
        SUM(AMOUNT) AS AMT_SUM
    FROM T0
    GROUP BY REF_DATE, RATING
),
T2 AS (
    SELECT 
        REF_DATE,
        RATING,
        AMT_SUM,
        LAG(AMT_SUM) OVER (PARTITION BY RATING ORDER BY REF_DATE) AS PREV_AMT_SUM
    FROM T1
),
T3 AS (
    SELECT 
        REF_DATE,
        RATING,
        AMT_SUM,
        AMT_SUM - COALESCE(PREV_AMT_SUM, 0) AS DIFF_CUMULATIVE,
        CASE 
            WHEN PREV_AMT_SUM IS NULL THEN 0
            ELSE (AMT_SUM - COALESCE(PREV_AMT_SUM, 0)) / COALESCE(PREV_AMT_SUM, 0)
        END AS PERC_CHANGE
    FROM T2
    WHERE 
        CASE 
            WHEN PREV_AMT_SUM IS NULL THEN 0
            ELSE (AMT_SUM - COALESCE(PREV_AMT_SUM, 0)) / COALESCE(PREV_AMT_SUM, 0)
        END <> 0
)
SELECT 
    REF_DATE,
    RATING,
    AMT_SUM,
    DIFF_CUMULATIVE,
    PERC_CHANGE
FROM 
    T3
ORDER BY 
    REF_DATE, RATING;

-- Q4 - TOP 5 COUNTRIES TO INVEST IN BY OPENING STORES?
/*
THE MOST INTERESTING MARKETS ARE INDIA, CHINA, AND JAPAN BASED ON THE GEOGRAPHICAL ORIGIN OF THE SURVEYED CLIENTS.
*/

SELECT 
    C3.COUNTRY,
    COUNT(DISTINCT C.CUSTOMER_ID) AS CUSTOMERS
FROM CUSTOMER C
JOIN ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID
JOIN CITY C2 ON A.CITY_ID = C2.CITY_ID
JOIN COUNTRY C3 ON C2.COUNTRY_ID = C3.COUNTRY_ID
WHERE C3.COUNTRY NOT IN (
    SELECT DISTINCT COUNTRY.COUNTRY
    FROM STORE
    JOIN ADDRESS ON STORE.ADDRESS_ID = ADDRESS.ADDRESS_ID 
    JOIN CITY ON ADDRESS.CITY_ID = CITY.CITY_ID
    JOIN COUNTRY ON COUNTRY.COUNTRY_ID = CITY.COUNTRY_ID
)
GROUP BY 
    C3.COUNTRY
ORDER BY
    CUSTOMERS DESC
LIMIT 5;